{% set version = "6.2.2" %}

package:
  name: pillow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pillow/Pillow-{{ version }}.tar.gz
  sha256: db9ff0c251ed066d367f53b64827cc9e18ccea001b986d08c265e53625dab950

build:
  number: 0
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - zlib
    - lcms2  # [not win]
    - libtiff
    - jpeg
    - freetype
    - tk
  run:
    - python
    - jpeg
    - zlib
    - freetype
    - libtiff
    - olefile
    - tk

test:
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms  # [not win]

about:
  home: https://pillow.readthedocs.io
  license: LicenseRef-PIL
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
