travis:
  secure:
    BINSTAR_TOKEN: cCqSD6x8dx8IYPAYmdP0APU99/LPPwAa2uoQsALmkK9bJlpdUiDvtyqAEr7Vi0p5nla1nqO2k5HA+gKYMvnR/x6nUE3D9JoUcNBUZjrWS9NeJDZ5wwJse9cBQcQw5rRNkRSETBS4R1EAcFM3BWb8z1h8ZgE6WFmFRsrpMZ0SWRxRX2YricgN7stbrEOEWLN9LK/Ox2jhQzHLw7qY8Y3GRQ/GNgk1rbH6FYbqKHJ8Cz+LwvJDgrOUgYRocMbWyjKB7qNzmyUfNOR1dXv1/6UrO+JTgXpvqCW74v1xntViZ1xjUMrlKBLF4fOf3TW1cN1j6/c9gWs5uDAhHlseq1zzAtx+9l/KUVbLxSbMGto4Iv0rjSG3Q+EPe4/HE7xfIsFbvP7DW7NV5voseNGcRNKzuMxfECiIcXnXO/ZmeKgwf+kJND9HCJLE7ZRgJW5mOlWk/JOISMwnfhH645mj6MLrKzZAjJhI3/4k7nRjy3C4om2awOi+cXgR8RMpTJcwdwaXjU8amBwARcRsb3+vaflBiTgnrTNTfP/Y2R4sx0WgOd9ZZfAAxDFXbshUaA9ZT1APi4RF766W9NP14DzLwXdClKP/yAp7Sf7YWpnLeyxeHT1Kc65TOeYQawADpFKC5zKjqa7TEpTL6GSqUlSKqBqWCgWcKXInMfuFdvqjQvggD3Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
